# Generated by Django 2.0.5 on 2018-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario_nome', models.CharField(max_length=100)),
                ('Usuario_idade', models.DateField()),
                ('Usuario_sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=100)),
            ],
        ),
    ]
