# Generated by Django 2.0.5 on 2018-05-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180525_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='Rota_motorista',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='Rota_veiculo',
        ),
    ]
