# Generated by Django 2.0.5 on 2018-05-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20180526_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='Veiculo_motorista',
        ),
    ]
