# Generated by Django 2.0.5 on 2018-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_veiculo_veiculo_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='Motorista_senha',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_senha',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
