# Generated by Django 2.0.5 on 2018-06-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20180527_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('Reserva_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='Motorista_idade',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='Motorista_sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_idade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_sexo',
        ),
        migrations.AddField(
            model_name='rota',
            name='Rota_data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='Rota_semanal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='Rota_veiculo',
            field=models.ManyToManyField(blank=True, to='registro.Veiculo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Veiculo_cor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Veiculo_motorista',
            field=models.ManyToManyField(blank=True, to='registro.Motorista'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Veiculo_placa',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='Motorista_senha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='Motorista_veiculo',
            field=models.ManyToManyField(blank=True, to='registro.Veiculo'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='Rota_horario',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='Veiculo_rota',
            field=models.ManyToManyField(blank=True, to='registro.Rota'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Reserva_motorista',
            field=models.ManyToManyField(to='registro.Motorista'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Reserva_rota',
            field=models.ManyToManyField(to='registro.Rota'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Reserva_usuario',
            field=models.ManyToManyField(to='registro.Usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Reserva_veiculo',
            field=models.ManyToManyField(to='registro.Veiculo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Usuario_reserva',
            field=models.ManyToManyField(to='registro.Reserva'),
        ),
    ]
