# Generated by Django 2.0.4 on 2018-08-17 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0006_auto_20180604_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='Motorista_contato',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='Motorista_nome',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='Motorista_senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_contato',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Usuario_senha',
        ),
        migrations.AddField(
            model_name='motorista',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
