# Generated by Django 2.1.3 on 2018-11-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20180817_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='Rota_semanal',
        ),
        migrations.AddField(
            model_name='rota',
            name='Motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Motorista'),
        ),
    ]
