# Generated by Django 2.1.3 on 2018-11-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20181101_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
