# Generated by Django 2.1.3 on 2018-11-13 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0013_auto_20181107_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='Motorista_veiculo',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='Veiculo_motorista',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
