# Generated by Django 2.1.1 on 2018-11-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_auto_20181107_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='Motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Motorista'),
        ),
    ]
