# Generated by Django 2.0.4 on 2018-11-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_auto_20181114_0736'),
        ('registro', '0014_auto_20181112_1655'),
    ]

    operations = [
    ]
