# Generated by Django 2.0.4 on 2018-11-18 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_merge_20181117_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='Reserva_motorista',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Reserva_veiculo',
        ),
        migrations.AlterField(
            model_name='rota',
            name='Motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
