# Generated by Django 2.0.4 on 2018-11-19 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_auto_20181117_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='Rota_localpartida',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
