# Generated by Django 2.1.3 on 2018-11-20 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_auto_20181120_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_contato',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Apenas números.')]),
        ),
    ]
