# Generated by Django 2.0.7 on 2018-11-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_auto_20181120_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='Veiculo_rota',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='Rota_veiculo',
        ),
        migrations.AddField(
            model_name='rota',
            name='Rota_veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Veiculo'),
        ),
    ]
